project:
  type: website
  output-dir: docs
website:
  title: "Intro 'Metrics at NJU"

  navbar:
    pinned: true
    background: "#341648"
    right:
      - href: index.qmd
        text: Home
      - about.qmd


  page-footer:
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})





format:
  html:
    theme: litera
    css: styles.css
    toc: true
    highlight-style: monokai
editor: visual

