project:
  type: website
  output-dir: docs
website:
  title: "Introductory Econometrics at NJU"

  navbar:
    pinned: true
    background: "#341648"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    highlight-style: monokai
editor: visual

